services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["php-fpm","-F"]
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      LOG_CHANNEL: stderr
    volumes:
      - ./:/var/www/html
      - storage:/var/www/html/storage
      - cache:/var/www/html/bootstrap/cache
    depends_on:
      db:
        condition: service_started

  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_started

  db:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: sirius
      MARIADB_USER: sirius
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  storage:
  cache:
