services:
  app:
    environment:
        APP_ENV: local
        APP_DEBUG: "true" 
        environment:
          - UID=${UID}
          - GID=${GID}
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    env_file: .env
    depends_on:
      db:
        condition: service_started

  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_started

  db:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: sirius
      MARIADB_USER: sirius
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3307:3306"   # host:container (podés quitarlo si no querés exponer DB al host)
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
